//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtitle.Downloader.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subtitle.Downloader.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; media=&quot;screen&quot; href=&quot;/~d/styles/rss2full.xsl&quot;?&gt;&lt;?xml-stylesheet type=&quot;text/css&quot; media=&quot;screen&quot; href=&quot;http://feeds.feedburner.com/~d/styles/itemcontent.css&quot;?&gt;&lt;rss xmlns:feedburner=&quot;http://rssnamespace.org/feedburner/ext/1.0&quot; version=&quot;2.0&quot;&gt;
        ///	&lt;channel&gt;
        ///	&lt;title&gt;Addic7ed.com - Quality Subtitles. - last new versions&lt;/title&gt;
        ///	&lt;link&gt;http://www.addic7ed.com/&lt;/link&gt;
        ///&lt;language&gt;en-us&lt;/language&gt;
        ///&lt;description&gt;Addic7ed.com - Quality Subtitles. - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Addic7edLastNewVersions {
            get {
                return ResourceManager.GetString("Addic7edLastNewVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; media=&quot;screen&quot; href=&quot;/~d/styles/rss2full.xsl&quot;?&gt;&lt;?xml-stylesheet type=&quot;text/css&quot; media=&quot;screen&quot; href=&quot;http://feeds.feedburner.com/~d/styles/itemcontent.css&quot;?&gt;&lt;rss xmlns:feedburner=&quot;http://rssnamespace.org/feedburner/ext/1.0&quot; version=&quot;2.0&quot;&gt;
        ///	&lt;channel&gt;
        ///	&lt;title&gt;Addic7ed.com - Quality Subtitles.  - last uploaded&lt;/title&gt;
        ///	&lt;link&gt;http://www.addic7ed.com/&lt;/link&gt;
        ///&lt;language&gt;en-us&lt;/language&gt;
        ///&lt;description&gt;Addic7ed.com - Quality Subtitles. - RS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Addic7edLastUploaded {
            get {
                return ResourceManager.GetString("Addic7edLastUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rss version=&quot;2.0&quot;&gt;
        ///	&lt;channel&gt;
        ///	&lt;title&gt;Addic7ed.com - Quality Subtitles.  - last uploaded&lt;/title&gt;
        ///	&lt;link&gt;http://www.addic7ed.com/&lt;/link&gt;
        ///&lt;language&gt;en-us&lt;/language&gt;
        ///&lt;description&gt;Addic7ed.com - Quality Subtitles. - RSS System&lt;/description&gt;
        ///&lt;generator&gt;addic7ed.com&lt;/generator&gt;
        ///			&lt;item&gt;&lt;title&gt;Sons of Anarchy - 06x12 - You Are My Sunshine&lt;/title&gt;&lt;link&gt;http://www.addic7ed.com/serie/Sons_of_Anarchy/6/12/You_Are_My_Sunshine&lt;/link&gt;&lt;description&gt;2HD, English&lt;/description&gt;&lt;pubDate&gt;Wed, 04 Dec 2013 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddictedHotspot {
            get {
                return ResourceManager.GetString("AddictedHotspot", resourceCulture);
            }
        }
    }
}
